source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Google/CloudMessaging'
pod 'RxSwift', '~> 2.0.0'

target 'RxGcm_swiftTests' do
    pod 'Nimble', '~> 3.0.0'
    pod 'RxTests', '~> 2.0'
end