source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'RxGcm_swift' do
    pod 'RxSwift', '~> 3.0'
    pod 'Google/CloudMessaging'
end

target 'RxGcm_swiftTests' do
    pod 'Nimble', '~> 5.0.0'
    pod 'RxTest', '~> 3.0'
end
